os: linux
dist: focal  # Ubuntu 20.04 build environment

git:
  submodules: true

language: python

matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.9-dev"
    - python: "nightly"
  allow_failures:
    - python: "3.9-dev"
    - python: "nightly"

before_install:
  - sudo apt-get install g++
  - sudo apt-get install cmake
  - sudo apt-get install bison
  - sudo apt-get install flex
  - sudo apt-get install python2-minimal

install:
  - pip install attrs
  - pip install importlab
  - pip install ninja
  - pip install pylint
  - pip install pyyaml
  - pip install six
  - pip install typed_ast

script:
  - python build_scripts/travis_script.py
