# https://docs.travis-ci.com/user/reference/osx
# https://github.com/simplejson/simplejson/blob/master/.travis.yml
# https://github.com/travis-ci/travis-ci/issues/9929
# https://docs.travis-ci.com/user/languages/python/
# https://github.com/travis-ci/travis-ci/issues/2312

git:
  submodules: true
  depth: 1

cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
  - name: MacOS Python 3.5
    env: PYENV_VERSION=3.5.9
    os: osx
    language: c++
  - name: MacOS Python 3.6
    env: PYENV_VERSION=3.6.10
    os: osx
    language: c++
  - name: MacOS Python 3.7
    env: PYENV_VERSION=3.7.7
    os: osx
    language: c++
  - name: MacOS Python 3.8
    env: PYENV_VERSION=3.8.3
    os: osx
    language: c++
  - name: manylinux2014-x86-64
    sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2014_x86_64:latest
         PLAT=manylinux2014_x86_64
  allow_failures:
  - name: MacOS Python 3.8

install:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      docker pull "$DOCKER_IMAGE" ;
    fi

script:
  - if [[ "$TRAVIS_OS_NAME" == 'linux' ]]; then
      docker container run --rm -e PLAT="$PLAT" -v "$(pwd)":/io $DOCKER_IMAGE /io/build_scripts/wheels/manylinux.sh ;
    fi
  - if [[ "$TRAVIS_OS_NAME" == 'osx' ]]; then
      ./build_scripts/wheels/macos.sh ;
    fi

after_success:
  - ls -1 {macos,linux}-wheelhouse/
