os: osx
# https://docs.travis-ci.com/user/reference/osx

git:
  submodules: true

language: python

matrix:
  include:
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"

before_install:
  # TODO: need xcode-select --install?
  - brew install -v bison
  - brew install -v cmake
  - brew install -v ninja
  - python -m pip install -U wheel setuptools

script:
  - CMAKE_PREFIX_PATH="$(brew --prefix bison)" python setup.py bdist_wheel
